// packages/photova/examples/vue/src/App.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import { createEditorUI, EditorUI } from 'brighten';

const containerRef = ref<HTMLElement | null>(null);
const fileInputRef = ref<HTMLInputElement | null>(null);
let editor: EditorUI | null = null;

onMounted(() => {
  if (containerRef.value) {
    editor = createEditorUI({
      container: containerRef.value,
      theme: 'dark',
      onExport: (blob) => {
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `edited-image-${Date.now()}.png`;
        link.click();
        URL.revokeObjectURL(url);
      },
    });

    editor.loadImage('https://picsum.photos/id/1015/1200/800');
  }
});

onUnmounted(() => {
  editor?.destroy();
});

const openFile = () => {
  fileInputRef.value?.click();
};

const handleFileSelect = async (event: Event) => {
  const input = event.target as HTMLInputElement;
  const file = input.files?.[0];
  if (file && editor) {
    await editor.loadImage(file);
  }
};

const handleExport = () => {
  editor?.export();
};
</script>

<template>
  <header class="header">
    <h1 class="title">Brighten - Vue Example</h1>
  </header>

  <main class="main">
    <div class="controls">
      <button class="button primary" @click="openFile">Open Image</button>
      <button class="button" @click="handleExport">Export</button>
      <input
        ref="fileInputRef"
        type="file"
        accept="image/*"
        style="display: none"
        @change="handleFileSelect"
      />
    </div>

    <div ref="containerRef" class="editor-container" />
  </main>
</template>

<style scoped>
.header {
  padding: 16px 24px;
  background: #111;
  border-bottom: 1px solid #333;
}

.title {
  font-size: 18px;
  font-weight: 600;
}

.main {
  flex: 1;
  display: flex;
  flex-direction: column;
  padding: 24px;
  gap: 16px;
}

.controls {
  display: flex;
  gap: 12px;
  flex-wrap: wrap;
}

.button {
  padding: 10px 20px;
  border-radius: 8px;
  border: 1px solid #444;
  background: #2a2a2a;
  color: #fff;
  font-size: 14px;
  cursor: pointer;
}

.button:hover {
  background: #3a3a3a;
}

.button.primary {
  background: #3b82f6;
  border-color: #3b82f6;
}

.button.primary:hover {
  background: #2563eb;
}

.editor-container {
  flex: 1;
  min-height: 500px;
  border-radius: 12px;
  overflow: hidden;
  border: 1px solid #333;
}
</style>

// examples/nextjs/app/page.tsx
'use client';

import { useRef, useEffect, useCallback } from 'react';
import { createEditorUI, EditorUI } from 'brighten';
import './globals.css';

export default function Home() {
  const containerRef = useRef<HTMLDivElement>(null);
  const editorRef = useRef<EditorUI | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (containerRef.current && !editorRef.current) {
      editorRef.current = createEditorUI({
        container: containerRef.current,
        theme: 'dark',
        onExport: (blob) => {
          const url = URL.createObjectURL(blob);
          const link = document.createElement('a');
          link.href = url;
          link.download = `edited-image-${Date.now()}.png`;
          link.click();
          URL.revokeObjectURL(url);
        },
      });

      editorRef.current.loadImage('https://picsum.photos/id/1015/1200/800');
    }

    return () => {
      if (editorRef.current) {
        editorRef.current.destroy();
        editorRef.current = null;
      }
    };
  }, []);

  const handleFileSelect = useCallback(async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file && editorRef.current) {
      await editorRef.current.loadImage(file);
    }
  }, []);

  const handleExport = useCallback(() => {
    editorRef.current?.export();
  }, []);

  return (
    <div style={styles.container}>
      <header style={styles.header}>
        <h1 style={styles.title}>Brighten - Next.js Example</h1>
      </header>

      <main style={styles.main}>
        <div style={styles.controls}>
          <button
            style={{ ...styles.button, ...styles.primaryButton }}
            onClick={() => fileInputRef.current?.click()}
          >
            Open Image
          </button>
          <button style={styles.button} onClick={handleExport}>
            Export
          </button>
          <input
            ref={fileInputRef}
            type="file"
            accept="image/*"
            style={{ display: 'none' }}
            onChange={handleFileSelect}
          />
        </div>

        <div ref={containerRef} style={styles.editorContainer} />
      </main>
    </div>
  );
}

const styles: Record<string, React.CSSProperties> = {
  container: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
  },
  header: {
    padding: '16px 24px',
    background: '#111',
    borderBottom: '1px solid #333',
  },
  title: {
    fontSize: '18px',
    fontWeight: 600,
  },
  main: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    padding: '24px',
    gap: '16px',
  },
  controls: {
    display: 'flex',
    gap: '12px',
    flexWrap: 'wrap',
  },
  button: {
    padding: '10px 20px',
    borderRadius: '8px',
    border: '1px solid #444',
    background: '#2a2a2a',
    color: '#fff',
    fontSize: '14px',
    cursor: 'pointer',
  },
  primaryButton: {
    background: '#3b82f6',
    borderColor: '#3b82f6',
  },
  editorContainer: {
    flex: 1,
    minHeight: '500px',
    borderRadius: '12px',
    overflow: 'hidden',
    border: '1px solid #333',
  },
};
